import { useState, useEffect, useRef } from 'react'
import { IMAGES } from '../assets/media'

function Counter({ target, suffix = '', duration = 2000 }) {
  const [val, setVal] = useState(0)
  const started = useRef(false)
  useEffect(() => {
    if (started.current) return
    started.current = true
    const start = performance.now()
    const tick = (now) => {
      const p = Math.min((now - start) / duration, 1)
      const e = 1 - Math.pow(1 - p, 3)
      setVal(Math.floor(e * target))
      if (p < 1) requestAnimationFrame(tick)
    }
    requestAnimationFrame(tick)
  }, [target, duration])
  return <>{val.toLocaleString()}{suffix}</>
}

const STATS = [
  { raw: null, target: 100, suffix: 'M+', label: 'Annual Visitors', sub: 'More than Disney World' },
  { raw: null, target: 1300, suffix: '+', label: 'Retail Tenants', sub: 'World-class brands' },
  { raw: '5.4M', label: 'Sq Ft of GLA', sub: 'Gross Leasable Area' },
  { raw: null, target: 160, suffix: '+', label: 'Dining Concepts', sub: 'Culinary destinations' },
  { raw: null, target: 200, suffix: '+', label: 'Nations Represented', sub: 'Global visitor base' },
  { raw: '$3B+', label: 'Annual Revenue', sub: 'Generated by ecosystem' },
]

export default function SlideStats({ isActive, goToCTA, goToNext }) {
  return (
    <>
      <div className="slide-bg" style={{ backgroundImage: `url(${IMAGES.skyline})` }} />
      <div className="ov-mid" style={{ background:'rgba(6,6,6,0.82)' }} />

      <div className="slide-content center" style={{ padding:'80px clamp(32px,6vw,100px) 60px' }}>
        <div className="a1">
          <div className="eyebrow">By the Numbers</div>
          <div className="gold-line gold-line-c" />
        </div>
        <h2 className="display a2" style={{ marginBottom:12 }}>Scale Beyond Imagination</h2>
        <p className="lead a3" style={{ maxWidth:500,margin:'0 auto 52px' }}>
          Numbers that tell a story no slide deck ever could
        </p>

        {/* Stats grid */}
        <div className="a4" style={{ display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:'1px',background:'var(--gold-dim)',width:'100%',maxWidth:900,margin:'0 auto 40px' }}>
          {STATS.map((s, i) => (
            <div key={i} style={{ background:'rgba(6,6,6,0.9)',padding:'clamp(20px,3vh,36px) 20px',textAlign:'center' }}>
              <div className="stat-num">
                {s.raw ? s.raw : (isActive ? <Counter target={s.target} suffix={s.suffix} /> : '0'+s.suffix)}
              </div>
              <div className="stat-lbl">{s.label}</div>
              <div className="stat-sub">{s.sub}</div>
            </div>
          ))}
        </div>

        {/* Location highlights */}
        <div className="a5" style={{ display:'flex',gap:20,justifyContent:'center',flexWrap:'wrap' }}>
          {[
            { icon:'🚇', label:'Direct Metro Access' },
            { icon:'🏙️', label:'Burj Khalifa Adjacency' },
            { icon:'✈️', label:'15 Min to Airport' },
            { icon:'💦', label:'Dubai Fountain Views' },
          ].map((item, i) => (
            <div key={i} style={{
              border:'1px solid var(--gold-dim)',padding:'12px 20px',
              display:'flex',alignItems:'center',gap:10,
              fontFamily:'var(--fs)',fontSize:'10px',letterSpacing:'0.12em',
              color:'var(--text2)',textTransform:'uppercase',
            }}>
              <span>{item.icon}</span><span>{item.label}</span>
            </div>
          ))}
        </div>

        <div className="a5" style={{ display:'flex',gap:16,marginTop:36,justifyContent:'center' }}>
          <button className="btn" onClick={goToNext}><span>See the Opportunity</span><span>→</span></button>
          <button className="btn-ghost" onClick={goToCTA}>Inquire Now →</button>
        </div>
      </div>

      <div style={{ position:'absolute',bottom:28,right:'clamp(32px,6vw,100px)',zIndex:10,fontFamily:'var(--fs)',fontSize:'8px',letterSpacing:'0.25em',color:'var(--text3)',textTransform:'uppercase' }}>02 / 10</div>
    </>
  )
}
